"""Polished Excel export for client-facing deliverables.

Generates a branded, presentation-ready .xlsx workbook with:
  - Summary sheet: client info, stats, strategy highlights
  - Variations sheet: all generated ad copy, grouped by source ad
  - Underperformers sheet: flagged ads with reasons and scores
"""
from __future__ import annotations

import io
from datetime import datetime, timezone
from pathlib import Path

from openpyxl import Workbook
from openpyxl.styles import (
    Font, PatternFill, Alignment, Border, Side, numbers,
)
from openpyxl.utils import get_column_letter
from openpyxl.drawing.image import Image as XlImage


# ── Brand colors ──
_DARK_BG = "1A1A2E"
_ACCENT = "E8FF47"
_ACCENT_DIM = "2A2D1A"
_HEADER_BG = "16213E"
_ROW_ALT = "0F3460"
_ROW_BASE = "1A1A2E"
_TEXT_WHITE = "F0F0F0"
_TEXT_MUTED = "94A3B8"
_DANGER = "FF6B6B"
_SUCCESS = "4ADE80"

_THIN_BORDER = Border(
    bottom=Side(style="thin", color="2A2D4E"),
)
_HEADER_BORDER = Border(
    bottom=Side(style="medium", color=_ACCENT),
)

_LOGO_PATH = Path(__file__).parent / "egc_logo.png"


def _style_header(ws, col_count: int, row: int = 1):
    """Apply header styling to a row."""
    for c in range(1, col_count + 1):
        cell = ws.cell(row=row, column=c)
        cell.font = Font(name="Calibri", size=10, bold=True, color=_ACCENT)
        cell.fill = PatternFill("solid", fgColor=_HEADER_BG)
        cell.alignment = Alignment(horizontal="left", vertical="center", wrap_text=True)
        cell.border = _HEADER_BORDER


def _style_data_row(ws, row: int, col_count: int, alt: bool = False):
    """Apply alternating row styling."""
    bg = _ROW_ALT if alt else _ROW_BASE
    for c in range(1, col_count + 1):
        cell = ws.cell(row=row, column=c)
        cell.font = Font(name="Calibri", size=10, color=_TEXT_WHITE)
        cell.fill = PatternFill("solid", fgColor=bg)
        cell.alignment = Alignment(vertical="top", wrap_text=True)
        cell.border = _THIN_BORDER


def _auto_width(ws, min_width: int = 12, max_width: int = 50):
    """Auto-fit column widths based on content."""
    for col_cells in ws.columns:
        col_letter = get_column_letter(col_cells[0].column)
        max_len = 0
        for cell in col_cells:
            val = str(cell.value or "")
            max_len = max(max_len, min(len(val), max_width))
        ws.column_dimensions[col_letter].width = max(min_width, max_len + 3)


def _add_logo(ws, row: int = 1, col: int = 1):
    """Add EGC logo to a worksheet if the file exists."""
    if _LOGO_PATH.exists():
        try:
            img = XlImage(str(_LOGO_PATH))
            img.width = 120
            img.height = 40
            ws.add_image(img, f"{get_column_letter(col)}{row}")
        except Exception:
            pass


def build_export_workbook(
    client_name: str,
    platform_name: str,
    platform_icon: str,
    slots: list,
    ad_sets: list[dict],
    underperformers: list | None = None,
    strategy_brief: dict | None = None,
    brand: str = "",
    product: str = "",
    total_ads: int = 0,
    num_underperformers: int = 0,
) -> bytes:
    """Build a polished, client-ready Excel workbook.

    Returns the workbook as bytes ready for st.download_button.
    """
    wb = Workbook()

    # ════════════════════════════════════════════════
    # SHEET 1: SUMMARY
    # ════════════════════════════════════════════════
    ws_summary = wb.active
    ws_summary.title = "Summary"
    ws_summary.sheet_properties.tabColor = _ACCENT

    # Dark background for all visible cells
    for row in range(1, 40):
        for col in range(1, 10):
            cell = ws_summary.cell(row=row, column=col)
            cell.fill = PatternFill("solid", fgColor=_DARK_BG)

    # Logo
    _add_logo(ws_summary, row=2, col=2)

    # Title block
    r = 5
    ws_summary.merge_cells("B5:H5")
    title_cell = ws_summary.cell(row=r, column=2, value="Ad Copy Variations")
    title_cell.font = Font(name="Calibri", size=22, bold=True, color=_ACCENT)
    title_cell.fill = PatternFill("solid", fgColor=_DARK_BG)

    r = 6
    ws_summary.merge_cells("B6:H6")
    sub_cell = ws_summary.cell(row=r, column=2, value=f"{platform_icon} {platform_name} · Generated by EGC Ad Optimizer")
    sub_cell.font = Font(name="Calibri", size=12, color=_TEXT_MUTED)
    sub_cell.fill = PatternFill("solid", fgColor=_DARK_BG)

    # Info block
    info_items = [
        ("Client", client_name),
        ("Brand", brand),
        ("Product", product),
        ("Platform", f"{platform_icon} {platform_name}"),
        ("Generated", datetime.now(timezone.utc).strftime("%B %d, %Y")),
    ]
    r = 8
    for label, value in info_items:
        ws_summary.cell(row=r, column=2, value=label).font = Font(
            name="Calibri", size=10, bold=True, color=_TEXT_MUTED)
        ws_summary.cell(row=r, column=2).fill = PatternFill("solid", fgColor=_DARK_BG)
        ws_summary.merge_cells(f"C{r}:E{r}")
        ws_summary.cell(row=r, column=3, value=value).font = Font(
            name="Calibri", size=10, color=_TEXT_WHITE)
        ws_summary.cell(row=r, column=3).fill = PatternFill("solid", fgColor=_DARK_BG)
        r += 1

    # Stats block
    r += 1
    stats = [
        ("Total Ads Analyzed", total_ads, _TEXT_WHITE),
        ("Underperformers Found", num_underperformers, _DANGER),
        ("Variations Generated", len(ad_sets), _ACCENT),
        ("Unique Source Ads", len(set(s.get("original_ad", "") for s in ad_sets)), _TEXT_WHITE),
    ]
    for label, value, color in stats:
        ws_summary.cell(row=r, column=2, value=label).font = Font(
            name="Calibri", size=10, color=_TEXT_MUTED)
        ws_summary.cell(row=r, column=2).fill = PatternFill("solid", fgColor=_DARK_BG)
        val_cell = ws_summary.cell(row=r, column=3, value=value)
        val_cell.font = Font(name="Calibri", size=14, bold=True, color=color)
        val_cell.fill = PatternFill("solid", fgColor=_DARK_BG)
        r += 1

    # Strategy highlights
    if strategy_brief:
        r += 1
        ws_summary.merge_cells(f"B{r}:H{r}")
        ws_summary.cell(row=r, column=2, value="Strategy Highlights").font = Font(
            name="Calibri", size=14, bold=True, color=_ACCENT)
        ws_summary.cell(row=r, column=2).fill = PatternFill("solid", fgColor=_DARK_BG)
        r += 1

        patterns = strategy_brief.get("dataset_patterns", {})
        for section_key, section_label in [
            ("what_top_performers_share", "What top performers share"),
            ("key_metric_insights", "Key data insights"),
        ]:
            items = patterns.get(section_key, [])
            if items:
                ws_summary.cell(row=r, column=2, value=section_label).font = Font(
                    name="Calibri", size=10, bold=True, color=_TEXT_WHITE)
                ws_summary.cell(row=r, column=2).fill = PatternFill("solid", fgColor=_DARK_BG)
                r += 1
                for item in items[:5]:
                    ws_summary.merge_cells(f"C{r}:H{r}")
                    ws_summary.cell(row=r, column=3, value=f"• {item}").font = Font(
                        name="Calibri", size=9, color=_TEXT_MUTED)
                    ws_summary.cell(row=r, column=3).fill = PatternFill("solid", fgColor=_DARK_BG)
                    r += 1

        cs = strategy_brief.get("creative_strategy", {})
        angles = cs.get("angles_to_test", [])
        if angles:
            ws_summary.cell(row=r, column=2, value="Recommended angles").font = Font(
                name="Calibri", size=10, bold=True, color=_TEXT_WHITE)
            ws_summary.cell(row=r, column=2).fill = PatternFill("solid", fgColor=_DARK_BG)
            r += 1
            for angle in angles[:5]:
                ws_summary.merge_cells(f"C{r}:H{r}")
                ws_summary.cell(row=r, column=3, value=f"→ {angle}").font = Font(
                    name="Calibri", size=9, color=_SUCCESS)
                ws_summary.cell(row=r, column=3).fill = PatternFill("solid", fgColor=_DARK_BG)
                r += 1

    ws_summary.column_dimensions["A"].width = 3
    ws_summary.column_dimensions["B"].width = 22
    ws_summary.column_dimensions["C"].width = 30
    for col_l in "DEFGH":
        ws_summary.column_dimensions[col_l].width = 15

    # ════════════════════════════════════════════════
    # SHEET 2: VARIATIONS (the main deliverable)
    # ════════════════════════════════════════════════
    ws_vars = wb.create_sheet("Variations")
    ws_vars.sheet_properties.tabColor = "60A5FA"

    # Headers
    headers = ["#", "Source Ad", "Angle"]
    for slot in slots:
        headers.append(slot.label)
        headers.append(f"{slot.label} Chars")
    headers.append("Rationale")
    col_count = len(headers)

    for c, h in enumerate(headers, 1):
        ws_vars.cell(row=1, column=c, value=h)
    _style_header(ws_vars, col_count)

    # Data rows
    prev_source = None
    group_idx = 0
    for i, ad_set in enumerate(ad_sets):
        row = i + 2
        source = ad_set.get("original_ad", "")

        # Alternate color per source ad group (not per row)
        if source != prev_source:
            group_idx += 1
            prev_source = source
        alt = group_idx % 2 == 0

        _style_data_row(ws_vars, row, col_count, alt=alt)

        ws_vars.cell(row=row, column=1, value=i + 1)
        ws_vars.cell(row=row, column=2, value=source)

        angle = ad_set.get("angle", "")
        ws_vars.cell(row=row, column=3, value=angle)

        col_offset = 4
        for slot in slots:
            text = ad_set.get(slot.key, "")
            char_count = len(text)
            ws_vars.cell(row=row, column=col_offset, value=text)
            # Make copy cells slightly larger font
            ws_vars.cell(row=row, column=col_offset).font = Font(
                name="Calibri", size=10, color=_TEXT_WHITE)

            char_cell = ws_vars.cell(row=row, column=col_offset + 1, value=char_count)
            # Color red if over limit
            if char_count > slot.char_limit:
                char_cell.font = Font(name="Calibri", size=9, color=_DANGER, bold=True)
            else:
                char_cell.font = Font(name="Calibri", size=9, color=_TEXT_MUTED)
            char_cell.alignment = Alignment(horizontal="center")
            col_offset += 2

        ws_vars.cell(row=row, column=col_offset, value=ad_set.get("rationale", ""))
        # Rationale in muted color
        ws_vars.cell(row=row, column=col_offset).font = Font(
            name="Calibri", size=9, italic=True, color=_TEXT_MUTED)

    # Column widths — copy columns wider
    ws_vars.column_dimensions["A"].width = 5   # #
    ws_vars.column_dimensions["B"].width = 35  # Source Ad
    ws_vars.column_dimensions["C"].width = 18  # Angle
    col_offset = 4
    for slot in slots:
        ws_vars.column_dimensions[get_column_letter(col_offset)].width = max(40, slot.char_limit // 2)
        ws_vars.column_dimensions[get_column_letter(col_offset + 1)].width = 8
        col_offset += 2
    ws_vars.column_dimensions[get_column_letter(col_offset)].width = 55  # Rationale

    # Freeze header row
    ws_vars.freeze_panes = "A2"

    # Row height for readability
    ws_vars.row_dimensions[1].height = 30
    for r in range(2, len(ad_sets) + 2):
        ws_vars.row_dimensions[r].height = 45

    # ════════════════════════════════════════════════
    # SHEET 3: UNDERPERFORMERS (analysis)
    # ════════════════════════════════════════════════
    if underperformers:
        ws_under = wb.create_sheet("Underperformers")
        ws_under.sheet_properties.tabColor = _DANGER

        u_headers = ["#", "Ad Name", "Score", "Reasons", "Fatigue"]
        for c, h in enumerate(u_headers, 1):
            ws_under.cell(row=1, column=c, value=h)
        _style_header(ws_under, len(u_headers))

        for i, u in enumerate(underperformers):
            row = i + 2
            _style_data_row(ws_under, row, len(u_headers), alt=i % 2 == 0)

            # Handle both dict and object underperformer formats
            if hasattr(u, "ad_data"):
                ad_data = u.ad_data
                reasons = u.reasons
                score = u.score
                fatigue = u.fatigue_signals if hasattr(u, "fatigue_signals") else []
            else:
                ad_data = u.get("ad_data", u)
                reasons = u.get("reasons", [])
                score = u.get("score", 0)
                fatigue = u.get("fatigue_signals", [])

            ad_name = ""
            for k in ("Ad name", "ad_name", "Ad Name", "Campaign name", "name", "Name"):
                if ad_data.get(k):
                    ad_name = str(ad_data[k])
                    break
            if not ad_name:
                ad_name = str(list(ad_data.values())[0]) if ad_data else f"Row {i}"

            ws_under.cell(row=row, column=1, value=i + 1)
            ws_under.cell(row=row, column=2, value=ad_name)

            score_cell = ws_under.cell(row=row, column=3, value=score)
            score_cell.font = Font(name="Calibri", size=10, bold=True, color=_DANGER)
            score_cell.number_format = "0.000"
            score_cell.alignment = Alignment(horizontal="center")

            ws_under.cell(row=row, column=4, value=" · ".join(reasons))
            ws_under.cell(row=row, column=5, value=" · ".join(fatigue) if fatigue else "")

        ws_under.column_dimensions["A"].width = 5
        ws_under.column_dimensions["B"].width = 45
        ws_under.column_dimensions["C"].width = 10
        ws_under.column_dimensions["D"].width = 50
        ws_under.column_dimensions["E"].width = 40
        ws_under.freeze_panes = "A2"

    # ════════════════════════════════════════════════
    # Write to bytes
    # ════════════════════════════════════════════════
    buf = io.BytesIO()
    wb.save(buf)
    buf.seek(0)
    return buf.getvalue()
